### ISSUE TITLE
Wiki Local development with Kubernetes error

### ISSUE THREAD

**Issue by andrea-mucci** [corda/corda-runtime-os#2452]
Hi All

In _Local development with Kubernetes_ wiki page, in the section  _Build the Corda Docker images_ the point 2 fail

```
git -C corda-cli-plugin-host checkout release/version-1.0.0-DevPreview2
error: pathspec 'release/version-1.0.0-DevPreview2' did not match any file(s) known to git
```

this is because the release tag does not exist

seems that the release tag must be:
release/version-5.0.0-DevPreview2

is that right?

Thanks in advance

**Comment by fenryka** [comment]
Good spot! Should be fixed now.
